--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: tutum
    version: v1
  name: tutum
spec: 

  replicas: 1
  selector: 
    matchLabels: 
      app: tutum
      version: v1
  template: 
    metadata: 
      labels: 
        app: tutum
        version: v1

    spec: 

      containers: 
        - 
          image: "tutum/hello-world"
          imagePullPolicy: Always
          name: tutum
          ports: 
#          - containerPort: 80 
          - name: httpport
            containerPort: 80
            hostPort: 80  
  

              
                    