spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sudha-G/MIcroservices/tree/master/configRepo.git
          
    
server:
  port: 8888
  

management:
  endpoints:
    web:
      exposure:
        include: "*"  
