spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Microservices/configRepo
          
    
server:
  port: 8888
  

management:
  endpoints:
    web:
      exposure:
        include: "*"  
