--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: configserver
    version: v1
  name: configserver
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: configserver
      version: v1
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: configserver
        version: v1
    spec: 
      containers: 
        - 

          image: "kapilshekharraina/configservervl01:1"
          imagePullPolicy: Always
          name: configserver
          ports: 
            - 
              containerPort: 8888
              hostPort: 8888
              name: httpport
          env: 
            - 
              name: configserver.git.url
              value: https://github.ibm.com/kapil-raina/VirtualMay2020LabsConfig.git
            - 
              name: github.username
              value: your_git_hub_userid
            - 
              name: github.password
              value: your_git_hub_access_token

            - 
              name: rabbitmq.host
              value: rabbitmq-master
            - 
              name: rabbitmq.port
              value: "5672"