spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.105:9411/}
  h2:
    console:
      enabled: ${productms.console.enabled:true}
      path: ${productms.console.path:/h2}
      settings:
        web-allow-others: true
  datasource:
    url: ${productms.datasource.url}
    username: ${productms.datasource.username:sa}
    password: ${productms.datasource.password" }
    driver-class-name: ${productms.datasource.driver:org.h2.driver}
  jpa:
    show-sql: true
 
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: ${productms.eureka.leaseRenewalIntervalInSeconds:2}
    leaseExpirationDurationInSeconds: ${productms.eureka.leaseExpirationDurationInSeconds:5}
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${productms.eureka.url:http://localhost:8761/eureka}
          
server:
  port: 0
  
feign:
  hystrix:
    enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"  
